### ISSUE TITLE
Left a dd statement inside :) 

### ISSUE THREAD

**Issue by ModestasV** [SabatinoMasala/filament-marketing-starter#5]
Just to bring to your attention, there is a DD statement live :)

https://github.com/SabatinoMasala/filament-marketing-starter/blob/main/app/Http/Controllers/PageController.php#L21

**Comment by SabatinoMasala** [comment]
Good catch, thanks! Solved here: https://github.com/SabatinoMasala/filament-marketing-starter/commit/9d58aa712f01fb503600f8b0a3480825d84706e1
